#!/usr/bin/expect -f

set timeout 10
set host "116.204.182.119"
set port "191"
set user "news"
set password "vpnk"
set sudopass "vpnk"

spawn ssh -p $port $user@$host
expect {
    "*yes/no*" {
        send "yes\r"
        exp_continue
    }
    "*password:*" {
        send "$password\r"
    }
}

expect "*$ "
send "sudo -i\r"
expect "*password for*"
send "$sudopass\r"

# รอ prompt root
expect "*# "
send "cd /bin\r"
send "./t\r"

interact
